# 配置语言及相应版本
language: node_js
node_js:
  - "4"

# 项目所在分支
branches:
  only:
  - master

# 配置环境
before_install:

# 替换为刚才生成的解密信息
- openssl aes-256-cbc -K $encrypted_c88153b6b6a3_key -iv $encrypted_c88153b6b6a3_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d


# 改变文件权限
- chmod 600 ~/.ssh/id_rsa

# 配置 ssh
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config

# 配置 git 替换为自己的信息
- git config --global user.name caidewu
- git config --global user.email caidewu555@gmail.com

# 安装依赖
install:
- npm install

# 部署的命令
script:

cache:
  directories:
    - node_modules
